// Generated by gencpp from file rosbridge_library/TestArrayRequest.msg
// DO NOT EDIT!


#ifndef ROSBRIDGE_LIBRARY_MESSAGE_TESTARRAYREQUEST_H
#define ROSBRIDGE_LIBRARY_MESSAGE_TESTARRAYREQUEST_H

#include <ros/service_traits.h>


#include <rosbridge_library/TestArrayRequestRequest.h>
#include <rosbridge_library/TestArrayRequestResponse.h>


namespace rosbridge_library
{

struct TestArrayRequest
{

typedef TestArrayRequestRequest Request;
typedef TestArrayRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TestArrayRequest
} // namespace rosbridge_library


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosbridge_library::TestArrayRequest > {
  static const char* value()
  {
    return "3d7cfb7e4aa0844868966efa8a264398";
  }

  static const char* value(const ::rosbridge_library::TestArrayRequest&) { return value(); }
};

template<>
struct DataType< ::rosbridge_library::TestArrayRequest > {
  static const char* value()
  {
    return "rosbridge_library/TestArrayRequest";
  }

  static const char* value(const ::rosbridge_library::TestArrayRequest&) { return value(); }
};


// service_traits::MD5Sum< ::rosbridge_library::TestArrayRequestRequest> should match
// service_traits::MD5Sum< ::rosbridge_library::TestArrayRequest >
template<>
struct MD5Sum< ::rosbridge_library::TestArrayRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosbridge_library::TestArrayRequest >::value();
  }
  static const char* value(const ::rosbridge_library::TestArrayRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbridge_library::TestArrayRequestRequest> should match
// service_traits::DataType< ::rosbridge_library::TestArrayRequest >
template<>
struct DataType< ::rosbridge_library::TestArrayRequestRequest>
{
  static const char* value()
  {
    return DataType< ::rosbridge_library::TestArrayRequest >::value();
  }
  static const char* value(const ::rosbridge_library::TestArrayRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosbridge_library::TestArrayRequestResponse> should match
// service_traits::MD5Sum< ::rosbridge_library::TestArrayRequest >
template<>
struct MD5Sum< ::rosbridge_library::TestArrayRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosbridge_library::TestArrayRequest >::value();
  }
  static const char* value(const ::rosbridge_library::TestArrayRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosbridge_library::TestArrayRequestResponse> should match
// service_traits::DataType< ::rosbridge_library::TestArrayRequest >
template<>
struct DataType< ::rosbridge_library::TestArrayRequestResponse>
{
  static const char* value()
  {
    return DataType< ::rosbridge_library::TestArrayRequest >::value();
  }
  static const char* value(const ::rosbridge_library::TestArrayRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSBRIDGE_LIBRARY_MESSAGE_TESTARRAYREQUEST_H
