// Generated by gencpp from file carla_ros_scenario_runner_types/ExecuteScenario.msg
// DO NOT EDIT!


#ifndef CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIO_H
#define CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIO_H

#include <ros/service_traits.h>


#include <carla_ros_scenario_runner_types/ExecuteScenarioRequest.h>
#include <carla_ros_scenario_runner_types/ExecuteScenarioResponse.h>


namespace carla_ros_scenario_runner_types
{

struct ExecuteScenario
{

typedef ExecuteScenarioRequest Request;
typedef ExecuteScenarioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteScenario
} // namespace carla_ros_scenario_runner_types


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenario > {
  static const char* value()
  {
    return "658be3a38e71a537a631efb452e9b5d1";
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenario&) { return value(); }
};

template<>
struct DataType< ::carla_ros_scenario_runner_types::ExecuteScenario > {
  static const char* value()
  {
    return "carla_ros_scenario_runner_types/ExecuteScenario";
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenario&) { return value(); }
};


// service_traits::MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest> should match
// service_traits::MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenario >
template<>
struct MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenario >::value();
  }
  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest> should match
// service_traits::DataType< ::carla_ros_scenario_runner_types::ExecuteScenario >
template<>
struct DataType< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest>
{
  static const char* value()
  {
    return DataType< ::carla_ros_scenario_runner_types::ExecuteScenario >::value();
  }
  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenarioResponse> should match
// service_traits::MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenario >
template<>
struct MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenarioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenario >::value();
  }
  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_ros_scenario_runner_types::ExecuteScenarioResponse> should match
// service_traits::DataType< ::carla_ros_scenario_runner_types::ExecuteScenario >
template<>
struct DataType< ::carla_ros_scenario_runner_types::ExecuteScenarioResponse>
{
  static const char* value()
  {
    return DataType< ::carla_ros_scenario_runner_types::ExecuteScenario >::value();
  }
  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIO_H
