// Generated by gencpp from file carla_ros_scenario_runner_types/ExecuteScenarioRequest.msg
// DO NOT EDIT!


#ifndef CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIOREQUEST_H
#define CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <carla_ros_scenario_runner_types/CarlaScenario.h>

namespace carla_ros_scenario_runner_types
{
template <class ContainerAllocator>
struct ExecuteScenarioRequest_
{
  typedef ExecuteScenarioRequest_<ContainerAllocator> Type;

  ExecuteScenarioRequest_()
    : scenario()  {
    }
  ExecuteScenarioRequest_(const ContainerAllocator& _alloc)
    : scenario(_alloc)  {
  (void)_alloc;
    }



   typedef  ::carla_ros_scenario_runner_types::CarlaScenario_<ContainerAllocator>  _scenario_type;
  _scenario_type scenario;





  typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteScenarioRequest_

typedef ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<std::allocator<void> > ExecuteScenarioRequest;

typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest > ExecuteScenarioRequestPtr;
typedef boost::shared_ptr< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest const> ExecuteScenarioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator1> & lhs, const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator2> & rhs)
{
  return lhs.scenario == rhs.scenario;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator1> & lhs, const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_ros_scenario_runner_types

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8702069c7110718714702d431553121";
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8702069c7110718ULL;
  static const uint64_t static_value2 = 0x714702d431553121ULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_ros_scenario_runner_types/ExecuteScenarioRequest";
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2020 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"CarlaScenario scenario\n"
"\n"
"================================================================================\n"
"MSG: carla_ros_scenario_runner_types/CarlaScenario\n"
"#\n"
"# Copyright (c) 2020 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"string name\n"
"string scenario_file\n"
;
  }

  static const char* value(const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.scenario);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteScenarioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_ros_scenario_runner_types::ExecuteScenarioRequest_<ContainerAllocator>& v)
  {
    s << indent << "scenario: ";
    s << std::endl;
    Printer< ::carla_ros_scenario_runner_types::CarlaScenario_<ContainerAllocator> >::stream(s, indent + "  ", v.scenario);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_ROS_SCENARIO_RUNNER_TYPES_MESSAGE_EXECUTESCENARIOREQUEST_H
