// Generated by gencpp from file carla_waypoint_types/GetActorWaypoint.msg
// DO NOT EDIT!


#ifndef CARLA_WAYPOINT_TYPES_MESSAGE_GETACTORWAYPOINT_H
#define CARLA_WAYPOINT_TYPES_MESSAGE_GETACTORWAYPOINT_H

#include <ros/service_traits.h>


#include <carla_waypoint_types/GetActorWaypointRequest.h>
#include <carla_waypoint_types/GetActorWaypointResponse.h>


namespace carla_waypoint_types
{

struct GetActorWaypoint
{

typedef GetActorWaypointRequest Request;
typedef GetActorWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetActorWaypoint
} // namespace carla_waypoint_types


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_waypoint_types::GetActorWaypoint > {
  static const char* value()
  {
    return "bf5553e309a0529c4c0d999d00a8b367";
  }

  static const char* value(const ::carla_waypoint_types::GetActorWaypoint&) { return value(); }
};

template<>
struct DataType< ::carla_waypoint_types::GetActorWaypoint > {
  static const char* value()
  {
    return "carla_waypoint_types/GetActorWaypoint";
  }

  static const char* value(const ::carla_waypoint_types::GetActorWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::carla_waypoint_types::GetActorWaypointRequest> should match
// service_traits::MD5Sum< ::carla_waypoint_types::GetActorWaypoint >
template<>
struct MD5Sum< ::carla_waypoint_types::GetActorWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_waypoint_types::GetActorWaypoint >::value();
  }
  static const char* value(const ::carla_waypoint_types::GetActorWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_waypoint_types::GetActorWaypointRequest> should match
// service_traits::DataType< ::carla_waypoint_types::GetActorWaypoint >
template<>
struct DataType< ::carla_waypoint_types::GetActorWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::carla_waypoint_types::GetActorWaypoint >::value();
  }
  static const char* value(const ::carla_waypoint_types::GetActorWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_waypoint_types::GetActorWaypointResponse> should match
// service_traits::MD5Sum< ::carla_waypoint_types::GetActorWaypoint >
template<>
struct MD5Sum< ::carla_waypoint_types::GetActorWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_waypoint_types::GetActorWaypoint >::value();
  }
  static const char* value(const ::carla_waypoint_types::GetActorWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_waypoint_types::GetActorWaypointResponse> should match
// service_traits::DataType< ::carla_waypoint_types::GetActorWaypoint >
template<>
struct DataType< ::carla_waypoint_types::GetActorWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::carla_waypoint_types::GetActorWaypoint >::value();
  }
  static const char* value(const ::carla_waypoint_types::GetActorWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_WAYPOINT_TYPES_MESSAGE_GETACTORWAYPOINT_H
