(cl:defpackage carla_waypoint_types-srv
  (:use )
  (:export
   "GETACTORWAYPOINT"
   "<GETACTORWAYPOINT-REQUEST>"
   "GETACTORWAYPOINT-REQUEST"
   "<GETACTORWAYPOINT-RESPONSE>"
   "GETACTORWAYPOINT-RESPONSE"
   "GETWAYPOINT"
   "<GETWAYPOINT-REQUEST>"
   "GETWAYPOINT-REQUEST"
   "<GETWAYPOINT-RESPONSE>"
   "GETWAYPOINT-RESPONSE"
  ))

