// Generated by gencpp from file rosapi/Nodes.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_NODES_H
#define ROSAPI_MESSAGE_NODES_H

#include <ros/service_traits.h>


#include <rosapi/NodesRequest.h>
#include <rosapi/NodesResponse.h>


namespace rosapi
{

struct Nodes
{

typedef NodesRequest Request;
typedef NodesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Nodes
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::Nodes > {
  static const char* value()
  {
    return "3d07bfda1268b4f76b16b7ba8a82665d";
  }

  static const char* value(const ::rosapi::Nodes&) { return value(); }
};

template<>
struct DataType< ::rosapi::Nodes > {
  static const char* value()
  {
    return "rosapi/Nodes";
  }

  static const char* value(const ::rosapi::Nodes&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::NodesRequest> should match
// service_traits::MD5Sum< ::rosapi::Nodes >
template<>
struct MD5Sum< ::rosapi::NodesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::Nodes >::value();
  }
  static const char* value(const ::rosapi::NodesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::NodesRequest> should match
// service_traits::DataType< ::rosapi::Nodes >
template<>
struct DataType< ::rosapi::NodesRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::Nodes >::value();
  }
  static const char* value(const ::rosapi::NodesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::NodesResponse> should match
// service_traits::MD5Sum< ::rosapi::Nodes >
template<>
struct MD5Sum< ::rosapi::NodesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::Nodes >::value();
  }
  static const char* value(const ::rosapi::NodesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::NodesResponse> should match
// service_traits::DataType< ::rosapi::Nodes >
template<>
struct DataType< ::rosapi::NodesResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::Nodes >::value();
  }
  static const char* value(const ::rosapi::NodesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_NODES_H
