// Generated by gencpp from file rosapi/SearchParam.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_SEARCHPARAM_H
#define ROSAPI_MESSAGE_SEARCHPARAM_H

#include <ros/service_traits.h>


#include <rosapi/SearchParamRequest.h>
#include <rosapi/SearchParamResponse.h>


namespace rosapi
{

struct SearchParam
{

typedef SearchParamRequest Request;
typedef SearchParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SearchParam
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::SearchParam > {
  static const char* value()
  {
    return "dfadc39f113c1cc6d7759508d8461d5a";
  }

  static const char* value(const ::rosapi::SearchParam&) { return value(); }
};

template<>
struct DataType< ::rosapi::SearchParam > {
  static const char* value()
  {
    return "rosapi/SearchParam";
  }

  static const char* value(const ::rosapi::SearchParam&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::SearchParamRequest> should match
// service_traits::MD5Sum< ::rosapi::SearchParam >
template<>
struct MD5Sum< ::rosapi::SearchParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::SearchParam >::value();
  }
  static const char* value(const ::rosapi::SearchParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::SearchParamRequest> should match
// service_traits::DataType< ::rosapi::SearchParam >
template<>
struct DataType< ::rosapi::SearchParamRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::SearchParam >::value();
  }
  static const char* value(const ::rosapi::SearchParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::SearchParamResponse> should match
// service_traits::MD5Sum< ::rosapi::SearchParam >
template<>
struct MD5Sum< ::rosapi::SearchParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::SearchParam >::value();
  }
  static const char* value(const ::rosapi::SearchParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::SearchParamResponse> should match
// service_traits::DataType< ::rosapi::SearchParam >
template<>
struct DataType< ::rosapi::SearchParamResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::SearchParam >::value();
  }
  static const char* value(const ::rosapi::SearchParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_SEARCHPARAM_H
