// Generated by gencpp from file rosapi/ServiceNode.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_SERVICENODE_H
#define ROSAPI_MESSAGE_SERVICENODE_H

#include <ros/service_traits.h>


#include <rosapi/ServiceNodeRequest.h>
#include <rosapi/ServiceNodeResponse.h>


namespace rosapi
{

struct ServiceNode
{

typedef ServiceNodeRequest Request;
typedef ServiceNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceNode
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::ServiceNode > {
  static const char* value()
  {
    return "bd2a0a45fd7a73a86c8d6051d5a6db8a";
  }

  static const char* value(const ::rosapi::ServiceNode&) { return value(); }
};

template<>
struct DataType< ::rosapi::ServiceNode > {
  static const char* value()
  {
    return "rosapi/ServiceNode";
  }

  static const char* value(const ::rosapi::ServiceNode&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::ServiceNodeRequest> should match
// service_traits::MD5Sum< ::rosapi::ServiceNode >
template<>
struct MD5Sum< ::rosapi::ServiceNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::ServiceNode >::value();
  }
  static const char* value(const ::rosapi::ServiceNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::ServiceNodeRequest> should match
// service_traits::DataType< ::rosapi::ServiceNode >
template<>
struct DataType< ::rosapi::ServiceNodeRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::ServiceNode >::value();
  }
  static const char* value(const ::rosapi::ServiceNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::ServiceNodeResponse> should match
// service_traits::MD5Sum< ::rosapi::ServiceNode >
template<>
struct MD5Sum< ::rosapi::ServiceNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::ServiceNode >::value();
  }
  static const char* value(const ::rosapi::ServiceNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::ServiceNodeResponse> should match
// service_traits::DataType< ::rosapi::ServiceNode >
template<>
struct DataType< ::rosapi::ServiceNodeResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::ServiceNode >::value();
  }
  static const char* value(const ::rosapi::ServiceNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_SERVICENODE_H
