(cl:defpackage carla_ackermann_msgs-msg
  (:use )
  (:export
   "<EGOVEHICLECONTROLCURRENT>"
   "EGOVEHICLECONTROLCURRENT"
   "<EGOVEHICLECONTROLINFO>"
   "EGOVEHICLECONTROLINFO"
   "<EGOVEHICLECONTROLMAXIMA>"
   "EGOVEHICLECONTROLMAXIMA"
   "<EGOVEHICLECONTROLSTATUS>"
   "EGOVEHICLECONTROLSTATUS"
   "<EGOVEHICLECONTROLTARGET>"
   "EGOVEHICLECONTROLTARGET"
  ))

