(cl:in-package carla_ackermann_msgs-msg)
(cl:export '(STATUS-VAL
          STATUS
          SPEED_CONTROL_ACTIVATION_COUNT-VAL
          SPEED_CONTROL_ACTIVATION_COUNT
          SPEED_CONTROL_ACCEL_DELTA-VAL
          SPEED_CONTROL_ACCEL_DELTA
          SPEED_CONTROL_ACCEL_TARGET-VAL
          SPEED_CONTROL_ACCEL_TARGET
          ACCEL_CONTROL_PEDAL_DELTA-VAL
          ACCEL_CONTROL_PEDAL_DELTA
          ACCEL_CONTROL_PEDAL_TARGET-VAL
          ACCEL_CONTROL_PEDAL_TARGET
          BRAKE_UPPER_BORDER-VAL
          BRAKE_UPPER_BORDER
          THROTTLE_LOWER_BORDER-VAL
          THROTTLE_LOWER_BORDER
))