// Generated by gencpp from file rosbridge_library/TestChar.msg
// DO NOT EDIT!


#ifndef ROSBRIDGE_LIBRARY_MESSAGE_TESTCHAR_H
#define ROSBRIDGE_LIBRARY_MESSAGE_TESTCHAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosbridge_library
{
template <class ContainerAllocator>
struct TestChar_
{
  typedef TestChar_<ContainerAllocator> Type;

  TestChar_()
    : data()  {
    }
  TestChar_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::rosbridge_library::TestChar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosbridge_library::TestChar_<ContainerAllocator> const> ConstPtr;

}; // struct TestChar_

typedef ::rosbridge_library::TestChar_<std::allocator<void> > TestChar;

typedef boost::shared_ptr< ::rosbridge_library::TestChar > TestCharPtr;
typedef boost::shared_ptr< ::rosbridge_library::TestChar const> TestCharConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosbridge_library::TestChar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosbridge_library::TestChar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosbridge_library::TestChar_<ContainerAllocator1> & lhs, const ::rosbridge_library::TestChar_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosbridge_library::TestChar_<ContainerAllocator1> & lhs, const ::rosbridge_library::TestChar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosbridge_library

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosbridge_library::TestChar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosbridge_library::TestChar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosbridge_library::TestChar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosbridge_library::TestChar_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosbridge_library::TestChar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosbridge_library::TestChar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosbridge_library::TestChar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b8d15902c8b049d5a32b4cb73fa86f5";
  }

  static const char* value(const ::rosbridge_library::TestChar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b8d15902c8b049dULL;
  static const uint64_t static_value2 = 0x5a32b4cb73fa86f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosbridge_library::TestChar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosbridge_library/TestChar";
  }

  static const char* value(const ::rosbridge_library::TestChar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosbridge_library::TestChar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char[] data\n"
;
  }

  static const char* value(const ::rosbridge_library::TestChar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosbridge_library::TestChar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestChar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosbridge_library::TestChar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosbridge_library::TestChar_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSBRIDGE_LIBRARY_MESSAGE_TESTCHAR_H
