// Generated by gencpp from file rosapi/GetParam.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_GETPARAM_H
#define ROSAPI_MESSAGE_GETPARAM_H

#include <ros/service_traits.h>


#include <rosapi/GetParamRequest.h>
#include <rosapi/GetParamResponse.h>


namespace rosapi
{

struct GetParam
{

typedef GetParamRequest Request;
typedef GetParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParam
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::GetParam > {
  static const char* value()
  {
    return "e36fd90759dbac1c5159140a7fa8c644";
  }

  static const char* value(const ::rosapi::GetParam&) { return value(); }
};

template<>
struct DataType< ::rosapi::GetParam > {
  static const char* value()
  {
    return "rosapi/GetParam";
  }

  static const char* value(const ::rosapi::GetParam&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::GetParamRequest> should match
// service_traits::MD5Sum< ::rosapi::GetParam >
template<>
struct MD5Sum< ::rosapi::GetParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::GetParam >::value();
  }
  static const char* value(const ::rosapi::GetParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::GetParamRequest> should match
// service_traits::DataType< ::rosapi::GetParam >
template<>
struct DataType< ::rosapi::GetParamRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::GetParam >::value();
  }
  static const char* value(const ::rosapi::GetParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::GetParamResponse> should match
// service_traits::MD5Sum< ::rosapi::GetParam >
template<>
struct MD5Sum< ::rosapi::GetParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::GetParam >::value();
  }
  static const char* value(const ::rosapi::GetParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::GetParamResponse> should match
// service_traits::DataType< ::rosapi::GetParam >
template<>
struct DataType< ::rosapi::GetParamResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::GetParam >::value();
  }
  static const char* value(const ::rosapi::GetParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_GETPARAM_H
