// Generated by gencpp from file rosapi/NodeDetails.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_NODEDETAILS_H
#define ROSAPI_MESSAGE_NODEDETAILS_H

#include <ros/service_traits.h>


#include <rosapi/NodeDetailsRequest.h>
#include <rosapi/NodeDetailsResponse.h>


namespace rosapi
{

struct NodeDetails
{

typedef NodeDetailsRequest Request;
typedef NodeDetailsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodeDetails
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::NodeDetails > {
  static const char* value()
  {
    return "e1d0ced5ab8d5edb5fc09c98eb1d46f6";
  }

  static const char* value(const ::rosapi::NodeDetails&) { return value(); }
};

template<>
struct DataType< ::rosapi::NodeDetails > {
  static const char* value()
  {
    return "rosapi/NodeDetails";
  }

  static const char* value(const ::rosapi::NodeDetails&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::NodeDetailsRequest> should match
// service_traits::MD5Sum< ::rosapi::NodeDetails >
template<>
struct MD5Sum< ::rosapi::NodeDetailsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::NodeDetails >::value();
  }
  static const char* value(const ::rosapi::NodeDetailsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::NodeDetailsRequest> should match
// service_traits::DataType< ::rosapi::NodeDetails >
template<>
struct DataType< ::rosapi::NodeDetailsRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::NodeDetails >::value();
  }
  static const char* value(const ::rosapi::NodeDetailsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::NodeDetailsResponse> should match
// service_traits::MD5Sum< ::rosapi::NodeDetails >
template<>
struct MD5Sum< ::rosapi::NodeDetailsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::NodeDetails >::value();
  }
  static const char* value(const ::rosapi::NodeDetailsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::NodeDetailsResponse> should match
// service_traits::DataType< ::rosapi::NodeDetails >
template<>
struct DataType< ::rosapi::NodeDetailsResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::NodeDetails >::value();
  }
  static const char* value(const ::rosapi::NodeDetailsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_NODEDETAILS_H
