// Generated by gencpp from file rosapi/ServiceType.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_SERVICETYPE_H
#define ROSAPI_MESSAGE_SERVICETYPE_H

#include <ros/service_traits.h>


#include <rosapi/ServiceTypeRequest.h>
#include <rosapi/ServiceTypeResponse.h>


namespace rosapi
{

struct ServiceType
{

typedef ServiceTypeRequest Request;
typedef ServiceTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceType
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::ServiceType > {
  static const char* value()
  {
    return "0e24a2dcdf70e483afc092a35a1f15f7";
  }

  static const char* value(const ::rosapi::ServiceType&) { return value(); }
};

template<>
struct DataType< ::rosapi::ServiceType > {
  static const char* value()
  {
    return "rosapi/ServiceType";
  }

  static const char* value(const ::rosapi::ServiceType&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::ServiceTypeRequest> should match
// service_traits::MD5Sum< ::rosapi::ServiceType >
template<>
struct MD5Sum< ::rosapi::ServiceTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::ServiceType >::value();
  }
  static const char* value(const ::rosapi::ServiceTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::ServiceTypeRequest> should match
// service_traits::DataType< ::rosapi::ServiceType >
template<>
struct DataType< ::rosapi::ServiceTypeRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::ServiceType >::value();
  }
  static const char* value(const ::rosapi::ServiceTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::ServiceTypeResponse> should match
// service_traits::MD5Sum< ::rosapi::ServiceType >
template<>
struct MD5Sum< ::rosapi::ServiceTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::ServiceType >::value();
  }
  static const char* value(const ::rosapi::ServiceTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::ServiceTypeResponse> should match
// service_traits::DataType< ::rosapi::ServiceType >
template<>
struct DataType< ::rosapi::ServiceTypeResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::ServiceType >::value();
  }
  static const char* value(const ::rosapi::ServiceTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_SERVICETYPE_H
