// Generated by gencpp from file rosapi/ServiceRequestDetailsResponse.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_SERVICEREQUESTDETAILSRESPONSE_H
#define ROSAPI_MESSAGE_SERVICEREQUESTDETAILSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rosapi/TypeDef.h>

namespace rosapi
{
template <class ContainerAllocator>
struct ServiceRequestDetailsResponse_
{
  typedef ServiceRequestDetailsResponse_<ContainerAllocator> Type;

  ServiceRequestDetailsResponse_()
    : typedefs()  {
    }
  ServiceRequestDetailsResponse_(const ContainerAllocator& _alloc)
    : typedefs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rosapi::TypeDef_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rosapi::TypeDef_<ContainerAllocator> >::other >  _typedefs_type;
  _typedefs_type typedefs;





  typedef boost::shared_ptr< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceRequestDetailsResponse_

typedef ::rosapi::ServiceRequestDetailsResponse_<std::allocator<void> > ServiceRequestDetailsResponse;

typedef boost::shared_ptr< ::rosapi::ServiceRequestDetailsResponse > ServiceRequestDetailsResponsePtr;
typedef boost::shared_ptr< ::rosapi::ServiceRequestDetailsResponse const> ServiceRequestDetailsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator1> & lhs, const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.typedefs == rhs.typedefs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator1> & lhs, const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosapi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d088db0da260a2cde072246a5f577519";
  }

  static const char* value(const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd088db0da260a2cdULL;
  static const uint64_t static_value2 = 0xe072246a5f577519ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosapi/ServiceRequestDetailsResponse";
  }

  static const char* value(const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TypeDef[] typedefs\n"
"\n"
"================================================================================\n"
"MSG: rosapi/TypeDef\n"
"string type\n"
"string[] fieldnames\n"
"string[] fieldtypes\n"
"int32[] fieldarraylen\n"
"string[] examples\n"
;
  }

  static const char* value(const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.typedefs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceRequestDetailsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosapi::ServiceRequestDetailsResponse_<ContainerAllocator>& v)
  {
    s << indent << "typedefs[]" << std::endl;
    for (size_t i = 0; i < v.typedefs.size(); ++i)
    {
      s << indent << "  typedefs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rosapi::TypeDef_<ContainerAllocator> >::stream(s, indent + "    ", v.typedefs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSAPI_MESSAGE_SERVICEREQUESTDETAILSRESPONSE_H
