// Generated by gencpp from file rosapi/TopicType.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_TOPICTYPE_H
#define ROSAPI_MESSAGE_TOPICTYPE_H

#include <ros/service_traits.h>


#include <rosapi/TopicTypeRequest.h>
#include <rosapi/TopicTypeResponse.h>


namespace rosapi
{

struct TopicType
{

typedef TopicTypeRequest Request;
typedef TopicTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TopicType
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::TopicType > {
  static const char* value()
  {
    return "0d30b3f53a0fd5036523a7141e524ddf";
  }

  static const char* value(const ::rosapi::TopicType&) { return value(); }
};

template<>
struct DataType< ::rosapi::TopicType > {
  static const char* value()
  {
    return "rosapi/TopicType";
  }

  static const char* value(const ::rosapi::TopicType&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::TopicTypeRequest> should match
// service_traits::MD5Sum< ::rosapi::TopicType >
template<>
struct MD5Sum< ::rosapi::TopicTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::TopicType >::value();
  }
  static const char* value(const ::rosapi::TopicTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::TopicTypeRequest> should match
// service_traits::DataType< ::rosapi::TopicType >
template<>
struct DataType< ::rosapi::TopicTypeRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::TopicType >::value();
  }
  static const char* value(const ::rosapi::TopicTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::TopicTypeResponse> should match
// service_traits::MD5Sum< ::rosapi::TopicType >
template<>
struct MD5Sum< ::rosapi::TopicTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::TopicType >::value();
  }
  static const char* value(const ::rosapi::TopicTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::TopicTypeResponse> should match
// service_traits::DataType< ::rosapi::TopicType >
template<>
struct DataType< ::rosapi::TopicTypeResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::TopicType >::value();
  }
  static const char* value(const ::rosapi::TopicTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_TOPICTYPE_H
