// Generated by gencpp from file rosapi/TopicTypeRequest.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_TOPICTYPEREQUEST_H
#define ROSAPI_MESSAGE_TOPICTYPEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosapi
{
template <class ContainerAllocator>
struct TopicTypeRequest_
{
  typedef TopicTypeRequest_<ContainerAllocator> Type;

  TopicTypeRequest_()
    : topic()  {
    }
  TopicTypeRequest_(const ContainerAllocator& _alloc)
    : topic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  _topic_type topic;





  typedef boost::shared_ptr< ::rosapi::TopicTypeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosapi::TopicTypeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TopicTypeRequest_

typedef ::rosapi::TopicTypeRequest_<std::allocator<void> > TopicTypeRequest;

typedef boost::shared_ptr< ::rosapi::TopicTypeRequest > TopicTypeRequestPtr;
typedef boost::shared_ptr< ::rosapi::TopicTypeRequest const> TopicTypeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosapi::TopicTypeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosapi::TopicTypeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosapi::TopicTypeRequest_<ContainerAllocator1> & lhs, const ::rosapi::TopicTypeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.topic == rhs.topic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosapi::TopicTypeRequest_<ContainerAllocator1> & lhs, const ::rosapi::TopicTypeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosapi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosapi::TopicTypeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosapi::TopicTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosapi::TopicTypeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8f94bae31b356b24d0427f80426d0c3";
  }

  static const char* value(const ::rosapi::TopicTypeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8f94bae31b356b2ULL;
  static const uint64_t static_value2 = 0x4d0427f80426d0c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosapi/TopicTypeRequest";
  }

  static const char* value(const ::rosapi::TopicTypeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string topic\n"
;
  }

  static const char* value(const ::rosapi::TopicTypeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopicTypeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosapi::TopicTypeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosapi::TopicTypeRequest_<ContainerAllocator>& v)
  {
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSAPI_MESSAGE_TOPICTYPEREQUEST_H
